### ISSUE TITLE
Trying to build with gradle 6.6 and latest Ghidra

### ISSUE THREAD

**Issue by cspencer49519** [jogolden/GhidraPS4Loader#8]
Does this require q specific version of Ghidra or gradle? I'm trying to build on macos 10.15.7 with gradle 6.6. I get the following errors:

graffix@Craigs-MacBook-Pro-2018 ghidra-plugin-PS4-loader % gradle

> Task :compileJava FAILED
/Users/graffix/Downloads/ghidra-plugin-PS4-loader/src/main/java/ghidraps4loader/GhidraPS4Loader.java:35: error: cannot find symbol
import ghidra.app.util.importer.MemoryConflictHandler;
                               ^
  symbol:   class MemoryConflictHandler
  location: package ghidra.app.util.importer
/Users/graffix/Downloads/ghidra-plugin-PS4-loader/src/main/java/ghidraps4loader/GhidraPS4Loader.java:176: error: cannot find symbol
            success = this.loadInto(provider, loadSpec, options, log, program, monitor, MemoryConflictHandler.ALWAYS_OVERWRITE);
                                                                                        ^
  symbol:   variable MemoryConflictHandler
  location: class GhidraPS4Loader
/Users/graffix/Downloads/ghidra-plugin-PS4-loader/src/main/java/ghidraps4loader/GhidraPS4Loader.java:257: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/graffix/Downloads/ghidra-plugin-PS4-loader/src/main/java/ghidraps4loader/GhidraPS4Loader.java:259: error: method validateOptions in class BinaryLoader cannot be applied to given types;
        return super.validateOptions(provider, loadSpec, options);
                    ^
  required: ByteProvider,LoadSpec,List<Option>,Program
  found:    ByteProvider,LoadSpec,List<Option>
  reason: actual and formal argument lists differ in length
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4s
1 actionable task: 1 executed
graffix@Craigs-MacBook-Pro-2018 ghidra-plugin-PS4-loader % sudo gradlr
sudo: gradlr: command not found
graffix@Craigs-MacBook-Pro-2018 ghidra-plugin-PS4-loader % sudo gradle

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/graffix/Downloads/ghidra-plugin-PS4-loader/build.gradle' line: 29

* What went wrong:
A problem occurred evaluating root project 'ghidra-plugin-PS4-loader'.
> GHIDRA_INSTALL_DIR is not defined!

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 557ms

**Comment by jogolden** [comment]
Something has changed n the new Ghidra I believe. If I have time at some point I can fix it, or you could look into it.

**Comment by cspencer49519** [comment]
I wish  possessed the knowledge to do that. Do you happen to know what version of ghidra it works on?

**Comment by nickl-** [comment]
Updated deprecation errors against Ghidra 10.2. see #10 

OpenJDK 18
Gradle 7.4.2

**Comment by marcussacana** [comment]
@nickl- I tried with your fork and I still got this error
```java
GhidraPS4Loader/src/main/java/ghidraps4loader/PS4ElfParser.java:98: error: constructor ElfHeader in class ElfHeader cannot be applied to given types;
                ElfHeader elfHeader = new ElfHeader(provider, msg -> Msg.error(PS4ElfParser.class, msg));
                                      ^
  required: no arguments
  found:    ByteProvider,(msg)->Msg[...] msg)
  reason: actual and formal argument lists differ in length
1 error
```

**Comment by marcussacana** [comment]
Okay, I fixed by changing the code like this:
```java
		MessageLog log = new MessageLog();
		ElfHeader elfHeader = ElfHeader.createElfHeader(MessageLogContinuesFactory.create(log), provider);
```
and adding this 2 imports
```java
import ghidra.app.util.importer.MessageLog;
import ghidra.app.util.importer.MessageLogContinuesFactory;
```

If someone more is with lazy to fix the build: 
[ghidra_10.1.5_PUBLIC_20220802_GhidraPS4Loader.zip](https://github.com/jogolden/GhidraPS4Loader/files/9245663/ghidra_10.1.5_PUBLIC_20220802_GhidraPS4Loader.zip)
